package:
  name: python-clanglite
  version: "3.8.1"

source:
  path: ../../..

build:
  number: 0
  string: py{{ CONDA_PY }}

about:
  home: http://autowig.rtfd.io/
  license: Apache License 2.0
  summary: A Python interface to the Clang library providing a relatively complete API for parsing source C++ code into an abstract syntax tree.

requirements:
  build:
    - libtoolchain
    - libboost_python-dev
    - python-toolchain
    - libclanglite
    - clang

test:   
  imports:
    - clanglite
