package:
  name: python-clanglite
  version: "3.8.1"

source:
  path: ../../..

build:
  number: 0
    
about:
  home: http://autowig.rtfd.io/
  license: Apache License 2.0
  summay: A Python interface to the Clang library providing a relatively complete API for parsing source C++ code into an abstract syntax tree.

requirements:
  build:
    - libtoolchain
    - python
    - libboost_python-dev
    - python-toolchain
    - libclanglite-dev
  run:
    - python
    - libclanglite

test:   
  imports:
    - clanglite
