package:
  name: python-clanglite
  version: "3.8.1"

source:
  path: ../../..

build:
  number: 0
  features:
    - vc12                [win]
  track_features:
    - vc12                 [win]

about:
  home: http://autowig.rtfd.io/
  license: Apache License 2.0
  summary: A Python interface to the Clang library providing a relatively complete API for parsing source C++ code into an abstract syntax tree.

requirements:
  build:
    - libtoolchain
    - libboost_python-dev
    - python-toolchain
    - libclanglite
    - clang
  run:
    - python

test:   
  imports:
    - clanglite
