##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (9)                        #
#                                                                                #
##################################################################################

package:
  name: python-clanglite
  version: "3.8.1"

source:
  path: ../../..

build:
  number: 0
    
about:
  home: autowig.readthedocs.org
  license: CeCILL

requirements:
  build:
    - python 2.7*
    - libboost
    - python-dev
    - clang
    - libclanglite
  run:
    - python 2.7*
    - clang
    - libclanglite
    - libboost

test:                                     [not win]
  commands:                               [not win]
    - python -c "from clanglite import *" [not win]
