##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (8)                        #
#                                                                                #
##################################################################################

build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install conda-build
  - conda build conda/libclang

on_success:
    - if %APPVEYOR_REPO_BRANCH% == "master" (
        anaconda login --username ${ANACONDA_USERNAME%%} --password ${ANACONDA_PASSWORD%%}
        CONDA_FILE=`conda build conda/libclang --output`
        anaconda upload --user ${ANACONDA_CHANNEL%%} ${CONDA_FILE%%}
        CONDA_FILE=`conda build conda/python-clanglite --output`
        anaconda upload --user ${ANACONDA_CHANNEL%%} ${CONDA_FILE%%}
      )
