build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install conda-build
  - conda build conda/libclang

on_success:
    - if %APPVEYOR_REPO_BRANCH% == "master" (
        anaconda login --username ${ANACONDA_USERNAME%%} --password ${ANACONDA_PASSWORD%%}
        CONDA_FILE=`conda build conda/libclang --output`
        anaconda upload --user ${ANACONDA_CHANNEL%%} ${CONDA_FILE%%}
        CONDA_FILE=`conda build conda/python-clanglite --output`
        anaconda upload --user ${ANACONDA_CHANNEL%%} ${CONDA_FILE%%}
      )
