##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (3)                        #
#                                                                                #
##################################################################################

about:
  authors:
  - Pierre Fernique
  - Christophe Pradal
  brief: A *Python* interface to **Clang**
  email: statiskit@googlegroups.com
  name: PyClangLite
  version: 0.1.0
authors:
  basename: AUTHORS.rst
  format: '* {name} <{email}> ({score})'
  plugin: commit
license:
  basename: LICENSE.rst
  plugin: CeCILL-C
  width: 78
version:
  plugin: semantic
