sudo: required
dist: trusty
language: cpp

os: linux

before_install:
    - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install conda-build
    - pip install python-coveralls
    - conda install libclang -c statiskit

before_script:
  - conda build conda/libclanglite -c statiskit --no-test
  - conda build conda/python-clanglite -c statiskit --no-test

script:
  - conda install python-clanglite -c statiskit --use-local
  
after_success:
  - coveralls
