platform:
  - x64

environment:
  CONDA_CACHE_DIR: '%SystemDrive%\cache'
  matrix:
    - BUILD_TARGETS: libllvm
      MINICONDA: "3"
    - BUILD_TARGETS: libclang
      MINICONDA: "3"
    - BUILD_TARGETS: libclanglite
      MINICONDA: "3"
    - BUILD_TARGETS: python-clanglite
      MINICONDA: "3"

cache:
  - C:\cache
  #- '%CONDA_CACHE_DIR%'

install:
  - git clone https://gist.github.com/a08b6eb1c97fad864de50601d70008c8.git config-appveyor
  - cd config-appveyor
  - call config.bat
  - cd ..
  - dir %CONDA_CACHE_DIR%

build_script:
  - dir %CONDA_CACHE_DIR%
  - cd conda
  - '%CMD_IN_ENV% call bld.bat'
  - cd ..
  - dir %CONDA_CACHE_DIR%
  
on_success:
  - cd conda
  - if "%APPVEYOR_REPO_BRANCH%"=="master" if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" if not "%ANACONDA_USERNAME%"=="" call upload.bat
  - cd ..
