platform:
  - x64

install:
  - git clone https://gist.github.com/a08b6eb1c97fad864de50601d70008c8.git config-appveyor
  - cd config-appveyor
  - call config.bat
  - cd ..
  
build_script:
  - cd conda
  - echo echo ON >> tmp.bat
  - more +7 "bld.bat" >> tmp.bat
  - del bld.bat
  - more tmp.bat >> bld.bat
  - '%CMD_IN_ENV% call bld.bat'
  - cd ..
  
on_success:
  - cd conda
  - if "%APPVEYOR_REPO_BRANCH%"=="master" if not "%ANACONDA_USERNAME%"=="" if not "%ANACONDA_PASSWORD%"=="" call upload.bat
  - cd ..
