package:
  name: python-clanglite
  version: "3.8.0"

source:
  path: ../..

build:
  number: 0

about:
  home: autowig.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - libclang
    - libclanglite
    - libboost
    - python-scons
    - pyyaml
  run:
    - libclang
    - libclanglite
    - libboost
    - python
    - numpy

test:
  commands:
    - python -c "from clanglite import *"
