package:
  name: python-clanglite
  version: "3.8.0"

source:
  path: ../..

build:
  number: 0

about:
  home: pyclanglite.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - libclang
    - libclanglite
    - libboost
    - scons
    - pyyaml
  run:
    - libclang
    - libclanglite
    - libboost
    - python
    - numpy
