# # -*-python-*-

# import os
# -*-python-*-

import os

Import("env")
pyenv = env.Clone()

pyenv.PrependUnique(LIBS = ['clanglite'])

exclude = """
""".split()

sources = [source for source in pyenv.Glob('*.*') if source.name not in exclude]

targets = pyenv.BoostPythonExtension("clanglite/__clanglite", sources, preserve_egg_dir=True)
Alias("py", targets)
Alias("install", targets)