package:
  name: llvm
  version: "3.8.1"

source:
  fn: llvm-3.8.1.src.tar.xz
  url: http://llvm.org/releases/3.8.1/llvm-3.8.1.src.tar.xz
  sha256: 6e82ce4adb54ff3afc18053d6981b6aed1406751b8742582ed50f04b5ab475f9
  patches:
    # https://llvm.org/bugs/show_bug.cgi?id=15356
    - {{ RECIPE_DIR }}/llvm-elf-relocation.patch
    # https://llvm.org/bugs/show_bug.cgi?id=25788
    - {{ RECIPE_DIR }}/llvm-parse-fp-constants.patch
    # https://llvm.org/bugs/show_bug.cgi?id=25565
    - {{ RECIPE_DIR }}/llvm-build-race-condition.patch
    # http://lists.llvm.org/pipermail/llvm-dev/2016-January/094520.html
    - {{ RECIPE_DIR }}/llvm-lto-static.patch                      [win]
    
build:
  number: 0
  skip: True      [osx]
  features:
    - vc12                [win]
  track_features:
    - vc12                 [win]
    
about:
  home: http://www.llvm.org/
  license: The University of Illinois/NCSA Open Source License
  summary: The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name "LLVM" itself is not an acronym; it is the full name of the project.

requirements:
  build:
    - libtoolchain
    - cmake
    - zlib
    - m2w64-xz          [py27 and win]
    - 7za               [win]
    - m2-patch          [win]
    - python
  run:
    - libtoolchain

test:
  commands:
  - llvm-config --libs
  - llc -version
