## Copyright [2017-2018] UMR MISTEA INRA, UMR LEPSE INRA,                ##
##                       UMR AGAP CIRAD, EPI Virtual Plants Inria        ##
## Copyright [2015-2016] UMR AGAP CIRAD, EPI Virtual Plants Inria        ##
##                                                                       ##
## This file is part of the AutoWIG project. More information can be     ##
## found at                                                              ##
##                                                                       ##
##     http://autowig.rtfd.io                                            ##
##                                                                       ##
## The Apache Software Foundation (ASF) licenses this file to you under  ##
## the Apache License, Version 2.0 (the "License"); you may not use this ##
## file except in compliance with the License. You should have received  ##
## a copy of the Apache License, Version 2.0 along with this file; see   ##
## the file LICENSE. If not, you may obtain a copy of the License at     ##
##                                                                       ##
##     http://www.apache.org/licenses/LICENSE-2.0                        ##
##                                                                       ##
## Unless required by applicable law or agreed to in writing, software   ##
## distributed under the License is distributed on an "AS IS" BASIS,     ##
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or       ##
## mplied. See the License for the specific language governing           ##
## permissions and limitations under the License.                        ##

# {% set version="4.0.1" %}
# {% set sha256="61738a735852c23c3bdbe52d035488cdb2083013f384d67c1ba36fabebd8769b" %}

{% set version="3.8.1" %}
{% set sha256="4cd3836dfb4b88b597e075341cae86d61c63ce3963e45c7fe6a8bf59bb382cdf" %}

package:
  name: clang
  version: {{ version }}
    
source:
  fn: cfe-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/cfe-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  # patches:
  #   - 0001-Allow-disabling-libXML.patch
  #   - 0002-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch
  #   - 0003-Fix-normalizeProgramName-s-handling-of-dots-ou.patch
  #   - 0004-Fix-B0-to-BBO-in-ThreadSafetyTraverse.patch
  
build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  skip: True        [osx]

about:
  home: http://www.llvm.org/
  license: The University of Illinois/NCSA Open Source License
  summary: The goal of the Clang project is to create a new C based language front-end (C, C++, Objective C/C++, OpenCL C and others) for the LLVM compiler.

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake
    - 7za                            [win]
    - patch                          [win]
  host:
    - llvm {{ version }}
    - python
    - zlib
  run:
    - llvm {{ version }}
    
test:
  commands:
  - clang++ -x c++ -v -E /dev/null   [not win]
  - clang -x c -v -E /dev/null       [not win]
  - clang++ -x c++ -v -E nul         [win]
  - clang -x c -v -E nul             [win]