package:
  name: libclang
  version: "3.8.1"
    
source:
  fn: cfe-3.8.1.src.tar.xz
  url: http://llvm.org/releases/3.8.1/cfe-3.8.1.src.tar.xz
  
build:
  number: 0
  script: source $RECIPE_DIR/linux_build.sh      [linux]
  script: source $RECIPE_DIR/osx_build.sh        [osx]

about:
  home: http://www.llvm.org/
  license: The University of Illinois/NCSA Open Source License
  summary: The goal of the Clang project is to create a new C based language front-end (C, C++, Objective C/C++, OpenCL C and others) for the LLVM compiler.

requirements:
  build:
    - llvm 3.8.1
    - cmake
    - zlib
    - m2w64-xz                       [py27 and win]
    - 7za                            [win]
  run:
    - libllvm 3.8.1

# test:
#   commands:
#   - clang++ -x c++ -v -E /dev/null   [not win]
#   - clang -x c -v -E /dev/null       [not win]
#   - clang++ -x c++ -v -E nul         [win]
#   - clang -x c -v -E nul             [win]