# -*-python-*-

import os
from SCons.Errors import EnvironmentError

Import("env")

cppenv = env.Clone(tools = ['cpp'])

cppenv.AppendUnique(CPPDEFINES = ['BUILD_LIBCLANGLITE'])

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.h*') if not source.name in exclude]

targets = cppenv.CppDev("clanglite", sources)
Alias("cpp-dev", targets)
Alias("cpp", targets)
Alias("install", targets)

Alias("cpp-dev", targets)
Alias("cpp", targets)
Alias("autowig", targets)
Alias("install", targets)
try:
    wigenv = cppenv.Clone(tools = ['wig'])

    targets = wigenv.BoostPythonWIG('clanglite', [target for target in targets if target.name.endswith('.h')],
                                    module='../py/_clanglite.cpp',
                                    decorator='../py/clanglite/_clanglite.py',
                                    parser_bootstrap=False,
                                    controller='AutoWIG.py',
                                    generator='boost_python_pattern',
                                    generator_closure=False,
                                    depends=[])
    Alias("autowig", targets)
    wigenv.Depends(targets, "cpp-dev")
except EnvironmentError:
    Alias("autowig", [])
    pass
except Exception:
    raise

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.cpp') if not source.name in exclude]

targets = cppenv.CppLib("clanglite", sources)
Alias("cpp-lib", targets)
Alias("cpp", targets)
Alias("install", targets)