# This file created by conda-build 3.0.15+5.g16cf4af
# ------------------------------------------------

package:
    name: libcxxabi
    version: 4.0.1

source:
    -   sha256: da783db1f82d516791179fe103c71706046561f7972b18f0049242dee6712b51
        url: http://releases.llvm.org/4.0.1/llvm-4.0.1.src.tar.xz
    -   folder: tools/clang
        patches:
            - 0001-clang-Allow-disabling-libXML.patch
            - 0002-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch
            - 0003-clang-Fix-normalizeProgramName-s-handling-of-dots-ou.patch
        sha256: 61738a735852c23c3bdbe52d035488cdb2083013f384d67c1ba36fabebd8769b
        url: http://releases.llvm.org/4.0.1/cfe-4.0.1.src.tar.xz
    -   folder: tools/polly
        sha256: b443bb9617d776a7d05970e5818aa49aa2adfb2670047be8e9f242f58e84f01a
        url: http://releases.llvm.org/4.0.1/polly-4.0.1.src.tar.xz
    -   folder: projects/compiler-rt
        patches:
            - 0001-cmake-Cache-results-of-find_darwin_sdk_dir.patch
            - 0002-compiler-rt-Determine-COMPILER_RT_SUPPORTED_ARCH-eve.patch
        sha256: a3c87794334887b93b7a766c507244a7cdcce1d48b2e9249fc9a94f2c3beb440
        url: http://releases.llvm.org/4.0.1/compiler-rt-4.0.1.src.tar.xz
    -   folder: projects/libunwind
        sha256: 3b072e33b764b4f9b5172698e080886d1f4d606531ab227772a7fc08d6a92555
        url: http://releases.llvm.org/4.0.1/libunwind-4.0.1.src.tar.xz
    -   folder: projects/libcxx
        sha256: 520a1171f272c9ff82f324d5d89accadcec9bc9f3c78de11f5575cdb99accc4c
        url: http://releases.llvm.org/4.0.1/libcxx-4.0.1.src.tar.xz
    -   folder: projects/libcxxabi
        sha256: 8f08178989a06c66cd19e771ff9d8ca526dd4a23d1382d63e416c04ea9fa1b33
        url: http://releases.llvm.org/4.0.1/libcxxabi-4.0.1.src.tar.xz
    -   folder: projects/openmp
        sha256: ec693b170e0600daa7b372240a06e66341ace790d89eaf4a843e8d56d5f4ada4
        url: http://releases.llvm.org/4.0.1/openmp-4.0.1.src.tar.xz
    -   folder: projects/tapi
        patches:
            - 0001-tapi-llvm-4.0.1-compat-remove-TimeValue-header-include.patch
            - 0002-tapi-llvm-4.0.1-compat-add-missing-StringSwitch-include.patch
            - 0003-tapi-llvm-4.0.1-compat-modernise-error-handling.patch
            - 0004-tapi-cross-compat.patch
        sha256: be2f3732c4ba7e9d78696fe43f0b31fa4963925ee6e4e5e11cc45603a83ff9a1
        url: https://opensource.apple.com/tarballs/tapi/tapi-1.30.tar.gz
    -   folder: cctools
        patches:
            - 001-remove_static_part.patch
            - 100-add_sdkroot_headers.patch
            - 110-import_to_include.patch
            - 120-fix_time_bugs.patch
            - 130-add_compileguards.patch
            - 140-remove_sysctl_osversion_detection.patch
            - 160-map_64bit_arches.patch
            - 170-fix_printf_format_bugs.patch
            - 180-add_CROSS_SYSROOT.patch
            - 190-default_arch.patch
            - 210-dont_typedef_NxConstantString.patch
            - 220-cross-prefixes-EXEEXT-and-progname_fixes.patch
            - 240-use_strerror.patch
            - 250-dont_assume_getattrlist.patch
            - 260-ppc64_reenable.patch
            - 270-dont_assume_vm_sync.patch
            - 280-missing_includes.patch
            - 290-error_as_weak_symbol.patch
            - 300-undef___unused_for_sysctl.patch
            - 340-win_O_BINARY.patch
            - 350-win_fileio_mode.patch
            - 360-win_TMPDIR_to_TEMP.patch
            - 370-win_execute.patch
            - 380-win_avoid_mmap_ofile.patch
            - 400-cctools-_WIN64-fixes.patch
            - 410-remove_inc_arch_sparc_reg_h_PC.patch
            - 420-autoconfiscate.patch
        sha256: ce66034fa35117f9ae76bbb7dd72d8068c405778fa42e877e8a13237a10c5cb7
        url: https://opensource.apple.com/tarballs/cctools/cctools-895.tar.gz
    -   folder: cctools/ld64
        patches:
            - 100-ld64-add_sdkroot_headers.patch
            - 150-ld64-allow_glibc_or_bsd_qsort_r.patch
            - 180-ld64-add_CROSS_SYSROOT.patch
            - 200-ld64-add_typename.patch
            - 280-ld64-missing_includes.patch
            - 320-ld64-extern_C_log2_only_if___APPLE__.patch
            - 330-ld64-extern_C___assert_rtn.patch
            - 340-ld64-win_O_BINARY.patch
            - 350-ld64-win_fileio_mode.patch
            - 390-ld64-_WIN64-fixes.patch
            - 420-ld64-autoconfiscate.patch
            - 500-ld64-add-fake-CrashReporterClient.h.patch
            - 510-ld64-fix-incorrect-fname-case.patch
            - 520-ld64-fix-usr-local-and-usr-ordering.patch
            - 530-ld64-add-conda-specific-env-vars-to-modify-lib-search-paths.patch
        sha256: 175d89c419e99d49a7a5f7e4196d3cef4c9e19cc17a425c332e86df6b516f7d7
        url: https://opensource.apple.com/tarballs/ld64/ld64-274.2.tar.gz
    -   folder: bootstrap
        sha256: 5f697801a46239c04251730b7ccccd3ebbacb9043ad381a061ae6812409e9eae
        url: http://releases.llvm.org/4.0.1/clang+llvm-4.0.1-x86_64-apple-darwin.tar.xz
    -   folder: bootstrap/dyld
        sha256: 13e370ed12c137f0153a96bab12e1d46896db07f8a40bac6b0529585ceac9260
        url: https://opensource.apple.com/tarballs/dyld/dyld-433.5.tar.gz
    -   folder: bootstrap/MacOSX10.9.sdk
        sha256: 113245eeae6c37571fa35bd844aab328acf08e0e645af0448c84f5b2195a4f56
        url: https://github.com/phracker/MacOSX-SDKs/releases/download/MacOSX10.11.sdk/MacOSX10.9.sdk.tar.xz

build:
  script: source $RECIPE_DIR/osx_build.sh [osx]
  skip: true [not osx]

requirements:
    build:
        - cmake-binary
        - autoconf
        - automake
about:
    description: libc++abi is a new implementation of low level support for a standard C++ library
    home: http://libcxxabi.llvm.org/
    license: University of Illinois/NCSA and MIT license
    summary: C++ Standard Library Support