package:
  name: libclanglite
  version: "3.8.1"

source:
  path: ../../..

build:
  number: 0
  run_exports:
    - libclanglite
  ignore_run_exports:
    - python

about:
  home: http://autowig.rtfd.io/
  license: Apache License 2.0
  summary: The C++ ClangLite Library is a lightweight library providing some interaction between the Clang and Boost.Python libraries in order to propose a Python interface to Clang.

requirements:
  build:
    - libtoolchain 
    - python-toolchain
    - libboost_python-dev
    - clang
  run:
    - python
    - clang