##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (26)                       #
#                                                                                #
##################################################################################

package:
  name: libclang
  version: "3.8.0"

source:
  git_url: https://github.com/llvm-mirror/llvm.git

build:
  number: 0
  script_env:
    - TOOLCHAIN # [not win]
  features:
    - {{ TOOLCHAIN }} # [not win]
  track_features:
    - {{ TOOLCHAIN }} # [not win]

about:
  home: http://www.llwm.org/
  license: The University of Illinois/NCSA Open Source License

requirements:
  build:
    - cmake
    - zlib
    - toolchain

test:
  commands:
  - llvm-config --libs   [not win]
  - llc -version         [not win]
  - clang++ -x c++ -v -E /dev/null [not win]
  - clang -x c -v -E /dev/null [not win]
