package:
  name: libclang
  version: "3.8.0"

source:
  git_url: https://github.com/llvm-mirror/llvm.git

build:
  number: 0

about:
  home: http://www.llwm.org/
  license: The University of Illinois/NCSA Open Source License

requirements:
  build:
    - cmake
    - zlib
    - system   [linux]
    - gcc-5    [linux]
    - libgcc-5 [linux]

  run:
    - zlib
    - system   [linux]
    - gcc-5    [linux]
    - libgcc-5 [linux]

test:
  commands:
  - llvm-config --libs   [not win]
  - llc -version         [not win]
