package:
  name: libclang
  version: "3.7"

source:
  git_url: https://github.com/llvm-mirror/llvm.git

build:
  number: 1

about:
  home: http://www.llwm.org/
  license: The University of Illinois/NCSA Open Source License

requirements:
  build:
    - cmake
    - gcc >=4.8 [not win]
    - libgcc [not win]
    - system [not win]
    - gnuwin32 [win]
  run:
    - system [not win]

test:
  commands:
    - llvm-config --libs   [not win]
    - llc -version         [not win]
