##################################################################################
#                                                                                #
# PyClangLite: Python bindings for Clang                                         #
#                                                                                #
# Homepage: http://pyclanglite.readthedocs.io/                                   #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (3)                        #
#                                                                                #
##################################################################################

package:
  name: libclanglite
  version: "3.8.1"

source:
  path: ../..

build:
  number: 0

about:
  home: pyclanglite.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - libdev 
    - python-dev
    - python
    - clang
    - libboost
    - python-scons
    - python-pkg
  run:
    - python
    - clang
    - libboost
